import { SessionProvider } from "@/libs/NextAuthProvider";
import ThemeRegistry from "@/theme/ThemeRegistry";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Header from "@/components/Header";
import Breadcrumb from "@/components/BreadCrumb";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <SessionProvider session={session}>
        <ThemeRegistry>
          <body className={inter.className}>
            {session && (
              <>
                <Header user={session?.user} appTitle="Ara Technical Test" />

                <Breadcrumb
                  homeElement="Home"
                  activeClasses="text-slate-500"
                  container="flex p-5 bg-gradient-to-r from-amber-200 to-green-500"
                  listClasses="hover:underline font-bold text-stone-500"
                  capitalizeLinks
                ></Breadcrumb>
              </>
            )}
            {children}
          </body>
        </ThemeRegistry>
      </SessionProvider>
    </html>
  );
}
