import { SessionProvider } from "@/libs/NextAuthProvider";
import ThemeRegistry from "@/theme/ThemeRegistry";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Header from "@/components/Header";
import Breadcrumb from "@/components/BreadCrumb";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Ara Tech Test",
  description: "Generated by create next app and developed by @laksmitawidya",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
 
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <ThemeRegistry>
          <body className="flex flex-col h-screen">
            <Header appTitle="Ara Technical Test" />
            <Breadcrumb />
            <main className="flex-1"> {children}</main>
            <Footer />
          </body>
        </ThemeRegistry>
      </SessionProvider>
    </html>
  );
}
